/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/67d53481233a52bf17ac7bcf.glb 
*/
import React, { useRef, useEffect } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useControls } from 'leva'
import * as THREE from "three";
import { isSpeakingAtom } from "./AudioState";
import { useAtom } from "jotai";

export function Avatar(props) {
    const { animations, wireframe, script } = props

    const { headFollow, cursorFollow } = useControls({
        headFollow: false,
        cursorFollow: false,

    });

    const group = useRef()
    const { scene } = useGLTF('models/67d53481233a52bf17ac7bcf.glb')
    const [isSpeaking, setIsSpeaking] = useAtom(isSpeakingAtom);

    const { animations: typingAnimation } = useFBX("animations/Typing.fbx")
    const { animations: StandingAnimation } = useFBX("animations/Standing.fbx")
    const { animations: FallingAnimation } = useFBX("animations/Falling.fbx")
    typingAnimation[0].name = "Typing";
    StandingAnimation[0].name = "Standing";
    FallingAnimation[0].name = "Falling";

    const animationList = React.useMemo(() => [typingAnimation[0], StandingAnimation[0], FallingAnimation[0]], [typingAnimation, StandingAnimation, FallingAnimation]);
    const { actions } = useAnimations(animationList, group);

    // Audio & Lip Sync Logic
    const audio = useRef(new Audio(""));
    const [lipsync, setLipsync] = React.useState(null);

    useEffect(() => {
        if (!script) {
            audio.current.pause();
            return;
        }

        const audioPath = `/Audios/${script}.ogg`;
        const jsonPath = `/Audios/${script}.json`;

        console.log("Attempting to play:", audioPath);

        // Load Audio
        audio.current.src = audioPath;
        audio.current.playbackRate = 1.3; // Increase speed
        audio.current.play().then(() => {
            setIsSpeaking(true);
        }).catch(e => {
            console.warn("Audio playback failed - Autoplay might be blocked. waiting for interaction.", e);
            const playOnInteract = () => {
                audio.current.play();
                setIsSpeaking(true);
                window.removeEventListener('click', playOnInteract);
                window.removeEventListener('keydown', playOnInteract);
                window.removeEventListener('touchstart', playOnInteract);
            };
            window.addEventListener('click', playOnInteract);
            window.addEventListener('keydown', playOnInteract);
            window.addEventListener('touchstart', playOnInteract);
        });

        audio.current.onended = () => {
            setIsSpeaking(false);
        };

        // Load Lip Sync JSON
        const loader = new THREE.FileLoader();
        loader.load(jsonPath, (data) => {
            try {
                setLipsync(JSON.parse(data));
            } catch (e) {
                console.error("Failed to parse lip sync JSON:", e);
            }
        });

        return () => {
            // Only pause if we are switching to a new script or unmounting
            // If we want it to persist across simple re-renders we might need to check dependencies better
            // But here script change implies track change.
            audio.current.pause();
        }

    }, [script]);

    const { nodes, materials } = useGraph(scene); // Move useGraph up to access morph targets

    useFrame((state) => {
        if (headFollow && group.current) {
            const head = group.current.getObjectByName("Head");
            if (head) head.lookAt(state.camera.position);
        }
        if (cursorFollow && group.current) {
            const spine = group.current.getObjectByName("Spine2");
            if (spine) {
                const target = new THREE.Vector3(state.mouse.x, state.mouse.y, 1);
                spine.lookAt(target);
            }
        }

        // Lip Sync Animation
        if (lipsync && audio.current) {
            const currentAudioTime = audio.current.currentTime;

            // Determine active viseme
            let activeViseme = null;
            for (let i = 0; i < lipsync.mouthCues.length; i++) {
                const cue = lipsync.mouthCues[i];
                if (currentAudioTime >= cue.start && currentAudioTime <= cue.end) {
                    activeViseme = corresponding[cue.value];
                    break;
                }
            }

            // Lerp all morph targets
            Object.values(corresponding).forEach((value) => {
                const targetIndexHead = nodes.Wolf3D_Head.morphTargetDictionary[value];
                const targetIndexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[value];

                if (targetIndexHead !== undefined && targetIndexTeeth !== undefined) {
                    // If this is the active viseme, target 1. If not, target 0.
                    const targetInfluence = (activeViseme === value) ? 1 : 0;

                    // Smoothly transition current value to target value
                    nodes.Wolf3D_Head.morphTargetInfluences[targetIndexHead] = THREE.MathUtils.lerp(
                        nodes.Wolf3D_Head.morphTargetInfluences[targetIndexHead],
                        targetInfluence,
                        0.1 // Adjust this value for speed (0.1 is smooth, 0.5 is snappy)
                    );

                    nodes.Wolf3D_Teeth.morphTargetInfluences[targetIndexTeeth] = THREE.MathUtils.lerp(
                        nodes.Wolf3D_Teeth.morphTargetInfluences[targetIndexTeeth],
                        targetInfluence,
                        0.1
                    );
                }
            });
        }
    });

    useEffect(() => {
        // Make sure animations prop exists and is a valid key in actions
        if (animations && actions && actions[animations]) {
            actions[animations].reset().fadeIn(0.2).play();
            return () => {
                if (actions[animations]) {
                    actions[animations].fadeOut(0.2);
                }
            };
        } else {
            console.warn(`Animation "${animations}" not found or actions not available`);
        }
    }, [animations, actions]);

    // Clone the scene - Removing this since we used useGraph(scene) directly above to get nodes early
    // const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    // const { nodes, materials } = useGraph(clone)

    // Apply wireframe effect
    useEffect(() => {
        if (materials) {
            Object.values(materials).forEach((material) => {
                if (material) material.wireframe = wireframe;
            });
        }
    }, [wireframe, materials]);

    const corresponding = {
        A: "viseme_PP",
        B: "viseme_kk",
        C: "viseme_I",
        D: "viseme_AA",
        E: "viseme_O",
        F: "viseme_U",
        G: "viseme_FF",
        H: "viseme_TH",
        X: "viseme_PP",
    };

    return (
        <group {...props} ref={group} dispose={null}>
            <group rotation-x={-Math.PI / 2}>
                <primitive object={nodes.Hips} />
                <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Headwear.geometry} material={materials.Wolf3D_Headwear} skeleton={nodes.Wolf3D_Headwear.skeleton} />
                <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
                <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
                <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
                <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
                <skinnedMesh frustumCulled={false} name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
                <skinnedMesh frustumCulled={false} name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
                <skinnedMesh frustumCulled={false} name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
                <skinnedMesh frustumCulled={false} name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
                <skinnedMesh frustumCulled={false} name="Wolf3D_Beard" geometry={nodes.Wolf3D_Beard.geometry} material={materials.Wolf3D_Beard} skeleton={nodes.Wolf3D_Beard.skeleton} morphTargetDictionary={nodes.Wolf3D_Beard.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Beard.morphTargetInfluences} />
            </group>
        </group>
    )
}

useGLTF.preload('models/67d53481233a52bf17ac7bcf.glb')
useFBX.preload("animations/Typing.fbx")
useFBX.preload("animations/Standing.fbx")
useFBX.preload("animations/Falling.fbx")